const API = '/api';
const state = {key:'', actor:'PJ', status:'pending', submissions:[], selected:null, detail:null, section:'discoveries'};
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];

function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function number(value){return Number(value||0).toLocaleString();}
function dateTime(value){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.valueOf())?'—':d.toLocaleString();}
function shortDate(value){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.valueOf())?'—':d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});}
function headers(){return {'X-Admin-Key':state.key,'Accept':'application/json'};}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className='toast'+(error?' error':'');el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,4500);}
async function api(path,options={}){const response=await fetch(API+path,{...options,headers:{...headers(),...(options.headers||{})}});let data={};try{data=await response.json();}catch{}if(!response.ok)throw new Error(data.detail||`Request failed (${response.status})`);return data;}

function lock(){sessionStorage.removeItem('wc_admin_key');sessionStorage.removeItem('wc_admin_actor');state.key='';state.selected=null;$('#dashboard').hidden=true;$('#loginPanel').hidden=false;$('#lockButton').hidden=true;$('#connectionBadge').textContent='Locked';$('#connectionBadge').className='connection-badge';$('#adminKeyInput').value='';}

async function unlock(event){event?.preventDefault();state.key=$('#adminKeyInput').value.trim();state.actor=$('#actorInput').value.trim()||'PJ';$('#loginError').hidden=true;try{await api('/admin/summary');sessionStorage.setItem('wc_admin_key',state.key);sessionStorage.setItem('wc_admin_actor',state.actor);$('#loginPanel').hidden=true;$('#dashboard').hidden=false;$('#lockButton').hidden=false;$('#connectionBadge').textContent='Admin connected';$('#connectionBadge').className='connection-badge online';await refreshAll();}catch(error){state.key='';$('#loginError').textContent=error.message;$('#loginError').hidden=false;}}

async function refreshAll(){await Promise.all([loadSummary(),loadSubmissions(),loadAudit()]);$('#lastRefresh').textContent=`Updated ${new Date().toLocaleTimeString()}`;}
async function loadSummary(){const data=await api('/admin/summary');const map={sumPending:data.pending_batches,sumPendingRecords:data.pending_discoveries,sumPublished:data.published_discoveries,sumMatches:data.published_pet_matches,sumApproved:data.approved_batches,sumRejected:data.rejected_batches};Object.entries(map).forEach(([id,value])=>{const el=document.getElementById(id);if(el)el.textContent=number(value);});}
async function loadSubmissions(){const data=await api(`/admin/submissions?status=${encodeURIComponent(state.status)}&limit=200`);state.submissions=data.items||[];renderQueue();if(state.selected){const match=state.submissions.find((item)=>item.id===state.selected);if(!match&&state.status==='pending'){clearDetail();}}}
function renderQueue(){const query=$('#queueSearch').value.trim().toLowerCase();const rows=state.submissions.filter((item)=>`${item.contributor} ${item.save_name} ${item.id}`.toLowerCase().includes(query));$('#queueEmpty').hidden=rows.length>0;$('#queueList').innerHTML=rows.map((item)=>`<button class="queue-item ${state.selected===item.id?'active':''}" data-id="${escapeHtml(item.id)}" type="button"><div class="queue-item-top"><strong>${escapeHtml(item.save_name)}</strong><time>${escapeHtml(shortDate(item.created_at))}</time></div><div class="queue-item-sub">${escapeHtml(item.contributor)}${item.platform?` • ${escapeHtml(item.platform)}`:''}</div><div class="queue-counts"><span>${number(item.discovery_count)} discoveries</span><span>${number(item.pet_match_count)} matches</span><span>${number(item.issue_count)} issues</span></div></button>`).join('');$$('.queue-item').forEach((button)=>button.addEventListener('click',()=>selectSubmission(button.dataset.id)));}
async function selectSubmission(id){state.selected=id;renderQueue();$('#reviewPlaceholder').hidden=true;$('#reviewContent').hidden=false;$('#recordTableWrap').innerHTML='<div class="review-placeholder"><p>Loading submission…</p></div>';try{state.detail=await api(`/admin/submissions/${encodeURIComponent(id)}`);renderDetail();}catch(error){toast(error.message,true);clearDetail();}}
function clearDetail(){state.selected=null;state.detail=null;$('#reviewContent').hidden=true;$('#reviewPlaceholder').hidden=false;renderQueue();}
function renderDetail(){const {batch,counts={}}=state.detail;$('#detailStatus').textContent=batch.status;$('#detailStatus').className=`detail-status ${batch.status}`;$('#detailSave').textContent=batch.save_name;$('#detailContributor').textContent=`Contributor: ${batch.contributor}${batch.platform?` • ${batch.platform}`:''}`;$('#detailDiscoveries').textContent=number(counts.discoveries??state.detail.discoveries?.length);$('#detailMatches').textContent=number(counts.pet_matches??state.detail.pet_matches?.length);$('#detailIssues').textContent=number(counts.issues??state.detail.issues?.length);$('#detailCreated').textContent=shortDate(batch.created_at);$('#existingNote').hidden=!batch.reviewer_note;$('#existingNote').textContent=batch.reviewer_note?`Reviewer note: ${batch.reviewer_note}`:'';$('#reviewActions').hidden=batch.status!=='pending';$('#actionResult').hidden=true;$('#reviewNote').value='';renderRecords();}
function currentRows(){if(!state.detail)return[];if(state.section==='raw')return[];return state.detail[state.section]||[];}
function renderRecords(){const raw=state.section==='raw';$('#rawPreview').hidden=!raw;$('#recordTableWrap').hidden=raw;$$('.record-tab').forEach((tab)=>tab.classList.toggle('active',tab.dataset.section===state.section));if(raw){$('#rawPreview').textContent=JSON.stringify(state.detail,null,2);$('#previewNote').textContent='Complete batch metadata and the available preview records.';return;}const query=$('#recordSearch').value.trim().toLowerCase();const all=currentRows();const filtered=all.filter((row)=>JSON.stringify(row).toLowerCase().includes(query));const shown=filtered.slice(0,250);const columns=[...new Set(shown.flatMap((row)=>Object.keys(row)))].slice(0,14);if(!shown.length){$('#recordTableWrap').innerHTML='<div class="review-placeholder"><p>No preview records match this filter.</p></div>';$('#previewNote').textContent=`0 of ${number(all.length)} preview records shown.`;return;}$('#recordTableWrap').innerHTML=`<table class="record-table"><thead><tr>${columns.map((key)=>`<th>${escapeHtml(key)}</th>`).join('')}</tr></thead><tbody>${shown.map((row)=>`<tr>${columns.map((key)=>`<td>${escapeHtml(typeof row[key]==='object'?JSON.stringify(row[key]):row[key])}</td>`).join('')}</tr>`).join('')}</tbody></table>`;const trunc=state.detail.truncated_to_500_per_section?' The API preview is capped at 500 per section; approval processes the full stored batch.':'';$('#previewNote').textContent=`Showing ${number(shown.length)} of ${number(filtered.length)} filtered preview records.${trunc}`;}
async function review(decision){if(!state.detail||state.detail.batch.status!=='pending')return;const note=$('#reviewNote').value.trim();const verb=decision==='approve'?'approve and publish':'reject';if(!confirm(`Are you sure you want to ${verb} “${state.detail.batch.save_name}”?`))return;const button=decision==='approve'?$('#approveButton'):$('#rejectButton');button.disabled=true;const original=button.textContent;button.textContent=decision==='approve'?'Publishing…':'Rejecting…';try{const result=await api(`/admin/submissions/${encodeURIComponent(state.selected)}/${decision}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:state.actor,note})});$('#actionResult').hidden=false;$('#actionResult').className='inline-alert success';$('#actionResult').textContent=decision==='approve'?`Published ${number(result.discoveries_added)} discoveries and ${number(result.pet_matches_added)} pet matches. Duplicates were safely skipped.`:'Submission rejected and retained in the audit history.';toast(decision==='approve'?'Submission approved and published.':'Submission rejected.');await refreshAll();clearDetail();}catch(error){toast(error.message,true);$('#actionResult').hidden=false;$('#actionResult').className='inline-alert error';$('#actionResult').textContent=error.message;}finally{button.disabled=false;button.textContent=original;}}
function exportDetail(){if(!state.detail)return;const blob=new Blob([JSON.stringify(state.detail,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${state.detail.batch.save_name.replace(/[^a-z0-9_-]+/gi,'_')}_${state.detail.batch.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function loadAudit(){try{const data=await api('/admin/audit?limit=30');const rows=data.items||[];$('#auditList').innerHTML=rows.length?rows.map((item)=>`<div class="audit-item"><span class="audit-symbol">${item.event_type.includes('approved')?'✓':'×'}</span><div><strong>${escapeHtml(item.event_type.replaceAll('_',' '))}</strong><small>${escapeHtml(item.actor)} • ${escapeHtml(item.batch_id||'No batch')}</small></div><time>${escapeHtml(dateTime(item.created_at))}</time></div>`).join(''):'<div class="empty-state"><p>No review events yet.</p></div>';}catch(error){$('#auditList').innerHTML=`<div class="inline-alert error">${escapeHtml(error.message)}</div>`;}}

$('#loginForm').addEventListener('submit',unlock);$('#lockButton').addEventListener('click',lock);$('#refreshButton').addEventListener('click',refreshAll);$('#refreshAudit').addEventListener('click',loadAudit);$('#queueSearch').addEventListener('input',renderQueue);$('#recordSearch').addEventListener('input',renderRecords);$('#approveButton').addEventListener('click',()=>review('approve'));$('#rejectButton').addEventListener('click',()=>review('reject'));$('#exportButton').addEventListener('click',exportDetail);$('#copyIdButton').addEventListener('click',async()=>{if(!state.selected)return;await navigator.clipboard.writeText(state.selected);toast('Submission ID copied.');});$$('.status-tab').forEach((tab)=>tab.addEventListener('click',async()=>{state.status=tab.dataset.status;$$('.status-tab').forEach((x)=>x.classList.toggle('active',x===tab));clearDetail();await loadSubmissions();}));$$('.record-tab').forEach((tab)=>tab.addEventListener('click',()=>{state.section=tab.dataset.section;renderRecords();}));

const savedKey=sessionStorage.getItem('wc_admin_key');const savedActor=sessionStorage.getItem('wc_admin_actor');if(savedActor)$('#actorInput').value=savedActor;if(savedKey){$('#adminKeyInput').value=savedKey;unlock();}
