(() => {
  'use strict';
  const $ = (selector) => document.querySelector(selector);
  const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const number = (value) => Number(value || 0).toLocaleString();
  const rankColor = (code) => ({S:'#ffd783',A:'#ffb5df',B:'#9d8cff',C:'#6de7ff'})[code] || '#6de7ff';
  function renderMissions(data){const start=new Date(data.week?.starts_at),end=new Date(data.week?.ends_at);$('#missionWeek').textContent=Number.isNaN(start.valueOf())?'Current UTC mission cycle':`${start.toLocaleDateString()} – ${new Date(end.valueOf()-1).toLocaleDateString()} · resets Monday UTC`;$('#missionGrid').innerHTML=(data.missions||[]).map((mission,index)=>`<article class="mission-card"><span>Mission ${String(index+1).padStart(2,'0')}</span><h3>${escapeHtml(mission.title)}</h3><p>${escapeHtml(mission.description)}</p><div class="mission-target"><strong>${number(mission.target)}</strong><small>${escapeHtml(mission.unit)}</small></div></article>`).join('')}
  function renderLeaders(data){const items=data.items||[];$('#leaderboard').innerHTML=items.length?items.map((item)=>{const m=item.metrics||{},missions=item.missions||[];return `<article class="leader-row"><span class="leader-position">#${number(item.position)}</span><span class="leader-rank" style="--rank-color:${rankColor(item.rank?.code)}" title="${escapeHtml(item.rank?.label)} rank">${escapeHtml(item.rank?.code||'C')}</span><div class="leader-name"><strong>${escapeHtml(item.display_name)}</strong><small>${escapeHtml(item.rank?.label||'Comet')} class · ${number(item.weekly_points)} this week</small><div class="leader-missions">${missions.map((mission)=>`<span class="${mission.completed?'complete':''}" title="${escapeHtml(mission.description)}">${escapeHtml(mission.title)} ${number(mission.progress)}/${number(mission.target)}</span>`).join('')}</div></div><div class="leader-metrics"><span>${number(m.discoveries)} discoveries</span><span>${number(m.images)} images</span><span>${number(m.verifications)} routes</span><span>${number(m.assets)} assets</span><span>${number(m.sightings)} sightings</span></div><div class="leader-points"><strong>${number(item.points)}</strong><small>evidence points</small></div></article>`}).join(''):'<div class="leaderboard-loading">No publicly attributed, approved contributions are available yet.</div>';$('#leaderboardPrivacy').textContent=data.privacy||''}
  async function load(){try{const response=await fetch('/api/contributors?limit=100',{headers:{Accept:'application/json'}}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.detail||`Leaderboard unavailable (${response.status}).`);renderMissions(data);renderLeaders(data)}catch(error){$('#missionGrid').innerHTML=`<div class="leaderboard-error">${escapeHtml(error.message)}</div>`;$('#leaderboard').innerHTML=`<div class="leaderboard-error">${escapeHtml(error.message)}</div>`}}
  load();
})();
