package nomanssave;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.lang.reflect.*;
import java.nio.file.*;
import java.util.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.plaf.basic.BasicTabbedPaneUI;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;

/** Keeps all native tab indices and model instances; replaces only application navigation. */
public final class WCEditorShell {
 private final Application app;private final JFrame frame;private final JTabbedPane tabs;
 private final JPanel root=new JPanel(new BorderLayout()),sidebar=new JPanel(new BorderLayout(0,12)),subnav=new JPanel(new FlowLayout(FlowLayout.LEFT,7,8));
 private final JLabel context=new JLabel(),status=new JLabel(),source=new JLabel(),sectionTitle=new JLabel();
 private final JButton save=new JButton("Review & Save"),rescan=new JButton("Rescan"),openFolder=new JButton("Add save folder…");
 private final DefaultListModel<WCEditorSaveDiscovery.Entry> sources=new DefaultListModel<WCEditorSaveDiscovery.Entry>();
 private final JList<WCEditorSaveDiscovery.Entry> sourceList=new JList<WCEditorSaveDiscovery.Entry>(sources);
 private final JComboBox<Section> sectionPicker=new JComboBox<Section>();
 private final LinkedHashMap<String,JToggleButton> navButtons=new LinkedHashMap<String,JToggleButton>();
 private final ArrayList<Section> sections=new ArrayList<Section>();
 private final WCEditorCodexPanel codex;private final WCEditorInventoryPanel inventory;private final WCEditorWarpPanel warp;private final WCEditorBasesPanel bases;private final WCEditorCorvettePanel corvettes;
 private final JComboBox slot,revision;
 private eY lastRoot,lastAccount,saveBaseline,accountBaseline;private boolean previousSaveDirty,previousAccountDirty,navigating,dark=true;private int inventoryIndex,warpIndex,baseJsonIndex,corvetteIndex,jsonIndex,archiveIndex,toolsIndex,codexIndex;
 private javax.swing.Timer poll;
 private static boolean installed;
 public static void install(Application app)throws Exception{if(installed)return;new WCEditorShell(app);installed=true;}
 private WCEditorShell(Application a)throws Exception{
  app=a;frame=a.g();tabs=(JTabbedPane)field("O");
  codex=new WCEditorCodexPanel(app);inventory=new WCEditorInventoryPanel(app);warp=new WCEditorWarpPanel(app);bases=new WCEditorBasesPanel(app);corvettes=new WCEditorCorvettePanel(app);
  inventoryIndex=append("Inventory hub",inventory);warpIndex=append("Warp",warp);baseJsonIndex=append("Base JSON",bases);corvetteIndex=append("Corvettes",corvettes);jsonIndex=append("JSON workspace",jsonPanel());archiveIndex=append("Expedition archive",archivePanel());toolsIndex=append("Tools & settings",toolsPanel());codexIndex=append("Wonder Codex",codex);
  inventory.setNavigator(index->showNative(index));
  add(0,"Overview","Overview");add(1,"Exosuit & currencies","Overview");add(inventoryIndex,"Inventory","Inventory");add(2,"Multitools","Inventory");add(3,"Starships","Fleet");add(corvetteIndex,"Corvettes","Fleet");add(5,"Freighter","Fleet");add(6,"Frigates","Fleet");add(4,"Squadron","Fleet");add(9,"Bases & storage","Bases");add(baseJsonIndex,"Base JSON","Bases");add(14,"Missions","Missions");add(warpIndex,"Warp","Warp");add(codexIndex,"Wonder Codex","Wonder Codex");add(7,"Vehicles","More");add(8,"Companions","More");add(10,"Settlements","More");add(11,"Unlocks & knowledge","More");add(12,"Milestones & reputation","More");add(13,"Account rewards","More");add(jsonIndex,"JSON workspace","More");add(archiveIndex,"Expedition archive","More");add(toolsIndex,"Tools & settings","More");
  for(Section s:sections)sectionPicker.addItem(s);
  sectionPicker.addActionListener(e->{if(!navigating){Section s=(Section)sectionPicker.getSelectedItem();if(s!=null)showNative(s.index);}});
  slot=new JComboBox(((JComboBox)field("R")).getModel());revision=new JComboBox(((JComboBox)field("S")).getModel());slot.setPrototypeDisplayValue("Slot 15 – Traveller, Creative");revision.setPrototypeDisplayValue("save2.hg · Oct 3, 14:20");revision.setRenderer(new DefaultListCellRenderer(){public Component getListCellRendererComponent(JList l,Object value,int i,boolean sel,boolean focus){JLabel label=(JLabel)super.getListCellRendererComponent(l,value,i,sel,focus);if(value instanceof fs){fs save=(fs)value;label.setText(save.toString()+" · "+Application.b(save.lastModified()));}return label;}});
  frame.getRootPane().putClientProperty("JRootPane.menuBarEmbedded",Boolean.FALSE);
  buildShell();applyTheme(true);WCEditorBranding.apply(frame);WCEditorCorvettePanel.installNativeGuards(app);interceptOpen();tabs.addChangeListener(e->syncSection());tabs.addPropertyChangeListener("UI",e->{if(!(tabs.getUI() instanceof HiddenTabsUI))SwingUtilities.invokeLater(()->tabs.setUI(new HiddenTabsUI()));});
  poll=new javax.swing.Timer(600,e->refreshStatus());poll.start();scan();refreshStatus();syncSection();
  frame.setTitle("Wonder Codex Editor · "+WCEditorLauncher.VERSION+" · "+WCEditorTazBridge.label());frame.setMinimumSize(new Dimension(1060,720));frame.setSize(Math.max(1240,frame.getWidth()),Math.max(830,frame.getHeight()));frame.setLocationRelativeTo(null);frame.revalidate();frame.repaint();SwingUtilities.invokeLater(()->WCEditorTazDialog.checkAtStartup(frame));
  WCCosmosBackup.log("WONDER_CODEX_DESKTOP installed version="+WCEditorLauncher.VERSION+" nativeTabs=14 allMenusRetained=true");
 }
 private Object field(String name)throws Exception{return WCCosmosHooks.field(app,name);}
 private static void set(Application app,String name,Object value)throws Exception{Field f=Application.class.getDeclaredField(name);f.setAccessible(true);f.set(app,value);}
 private Object invoke(String method)throws Exception{Method m=Application.class.getDeclaredMethod(method);m.setAccessible(true);try{return m.invoke(app);}catch(InvocationTargetException e){Throwable cause=e.getCause();if(cause instanceof Exception)throw(Exception)cause;throw e;}}
 private int append(String title,JComponent c){int n=tabs.getTabCount();tabs.addTab(title,c);return n;}
 private void add(int index,String name,String group){sections.add(new Section(index,name,group));}
 private static JLabel label(String text,int size,boolean bold){JLabel l=new JLabel(text);l.setFont(new Font("Segoe UI",bold?Font.BOLD:Font.PLAIN,size));return l;}
 private static JPanel row(Component...items){JPanel p=new JPanel(new FlowLayout(FlowLayout.LEFT,9,0));for(Component c:items)p.add(c);return p;}
 private JButton action(String text,Runnable action){JButton b=new JButton(text);b.addActionListener(e->action.run());return b;}
 private JPanel stack(){JPanel p=new JPanel();p.setLayout(new BoxLayout(p,BoxLayout.Y_AXIS));return p;}
 private void buildShell()throws Exception{
  JPanel header=new JPanel(new BorderLayout());header.setBorder(new EmptyBorder(18,22,18,22));JPanel brand=stack();brand.add(label("WONDER CODEX",20,true));brand.add(label("SAVE EDITOR",10,false));header.add(brand,BorderLayout.WEST);JPanel badge=row(label("COSMOS  ·  "+WCEditorLauncher.VERSION,11,false),action("About",()->about()));header.add(badge,BorderLayout.EAST);root.add(header,BorderLayout.NORTH);
  sidebar.setPreferredSize(new Dimension(245,650));sidebar.setBorder(new EmptyBorder(18,15,16,15));sidebar.add(row(label("SAVES ON THIS PC",11,true),rescan),BorderLayout.NORTH);
  sourceList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);sourceList.setFixedCellHeight(70);sourceList.setCellRenderer(new DefaultListCellRenderer(){@Override public Component getListCellRendererComponent(JList list,Object value,int index,boolean selected,boolean focus){JLabel c=(JLabel)super.getListCellRendererComponent(list,value,index,selected,focus);if(value instanceof WCEditorSaveDiscovery.Entry){WCEditorSaveDiscovery.Entry e=(WCEditorSaveDiscovery.Entry)value;c.setText("<html><b>"+html(friendlyAccount(e))+"</b><br><font size='3'>"+html(e.platform)+"</font></html>");c.setToolTipText(e.path.toString());}c.setBorder(new EmptyBorder(10,10,10,10));return c;}});
  sourceList.addMouseListener(new MouseAdapter(){public void mouseClicked(MouseEvent e){if(e.getClickCount()==2)openSelected();}});sourceList.getInputMap().put(KeyStroke.getKeyStroke("ENTER"),"open-source");sourceList.getActionMap().put("open-source",new AbstractAction(){public void actionPerformed(ActionEvent e){openSelected();}});
  JScrollPane sourceScroll=new JScrollPane(sourceList);sourceScroll.setBorder(BorderFactory.createEmptyBorder());sidebar.add(sourceScroll,BorderLayout.CENTER);JPanel sideBottom=stack();sideBottom.add(action("Open selected account",()->openSelected()));sideBottom.add(Box.createVerticalStrut(8));sideBottom.add(openFolder);sideBottom.add(Box.createVerticalStrut(10));JLabel note=new JLabel("<html>Steam · GOG · Xbox / Game Pass<br>Choose an account, then a save slot.</html>");note.setFont(note.getFont().deriveFont(11f));sideBottom.add(note);sidebar.add(sideBottom,BorderLayout.SOUTH);
  rescan.addActionListener(e->scan());openFolder.addActionListener(e->chooseFolder());root.add(sidebar,BorderLayout.WEST);
  JPanel main=new JPanel(new BorderLayout());JPanel top=stack();JPanel contextRow=new JPanel(new BorderLayout(12,0));contextRow.setBorder(new EmptyBorder(14,22,12,22));JPanel contextText=stack();context.setFont(context.getFont().deriveFont(Font.BOLD,15f));source.setFont(source.getFont().deriveFont(11f));contextText.add(context);contextText.add(Box.createVerticalStrut(4));contextText.add(source);contextRow.add(contextText,BorderLayout.CENTER);contextRow.add(row(label("Slot",11,false),slot,label("Revision",11,false),revision),BorderLayout.EAST);top.add(contextRow);
  JPanel nav=new JPanel(new FlowLayout(FlowLayout.LEFT,6,0));nav.setBorder(new EmptyBorder(6,19,7,19));ButtonGroup group=new ButtonGroup();for(String n:new String[]{"Overview","Inventory","Fleet","Bases","Missions","Warp","Wonder Codex","More"}){JToggleButton b=new JToggleButton(n);b.putClientProperty("JButton.buttonType","toolBarButton");b.setMargin(new Insets(11,9,11,9));b.addActionListener(e->{for(Section s:sections)if(s.group.equals(n)){showNative(s.index);return;}});group.add(b);nav.add(b);navButtons.put(n,b);}top.add(nav);
  JPanel secondary=new JPanel(new BorderLayout(10,0));secondary.setBorder(new EmptyBorder(0,20,3,20));secondary.add(subnav,BorderLayout.CENTER);secondary.add(row(label("All sections",11,false),sectionPicker),BorderLayout.EAST);top.add(secondary);main.add(top,BorderLayout.NORTH);
  tabs.setBorder(new EmptyBorder(10,16,12,16));main.add(tabs,BorderLayout.CENTER);
  JPanel footer=new JPanel(new BorderLayout());footer.setBorder(new EmptyBorder(13,22,13,22));JPanel messages=stack();status.setFont(status.getFont().deriveFont(Font.BOLD,12f));messages.add(status);messages.add(label("A verified backup is created before saving.",11,false));messages.add(WCEditorTazDialog.creatorLink());footer.add(messages,BorderLayout.CENTER);save.putClientProperty("JButton.buttonType","roundRect");save.addActionListener(e->reviewSave());footer.add(row(action("Backups",()->openBackups()),save),BorderLayout.EAST);main.add(footer,BorderLayout.SOUTH);root.add(main,BorderLayout.CENTER);frame.setContentPane(root);
 }
 private void interceptOpen(){JMenuItem item=findMenu(frame.getJMenuBar(),"Open File/Path");if(item!=null){for(ActionListener listener:item.getActionListeners())item.removeActionListener(listener);item.addActionListener(e->{JFileChooser chooser=new JFileChooser();chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);chooser.setDialogTitle("Open supported save file or folder");if(chooser.showOpenDialog(frame)==JFileChooser.APPROVE_OPTION)try{if(WCEditorStorage.open(app,chooser.getSelectedFile().toPath())){refreshStatus();showNative(0);}}catch(Exception ex){error("Open save",ex);}});}}
 private void applyTheme(boolean useDark){dark=useDark;try{UIManager.setLookAndFeel(useDark?new FlatDarkLaf():new FlatLightLaf());Color bg=useDark?new Color(10,23,38):new Color(240,244,250),panel=useDark?new Color(16,32,50):Color.WHITE,control=useDark?new Color(23,43,65):new Color(244,247,251),text=useDark?new Color(230,239,249):new Color(28,48,70),line=useDark?new Color(42,63,86):new Color(210,221,234),selected=useDark?new Color(36,65,101):new Color(217,232,255);
  for(String k:new String[]{"Panel.background","Viewport.background","TabbedPane.background","MenuBar.background"})UIManager.put(k,panel);for(String k:new String[]{"TextField.background","FormattedTextField.background","TextArea.background","ComboBox.background","Spinner.background","Button.background","List.background","Table.background"})UIManager.put(k,control);for(String k:new String[]{"Label.foreground","Button.foreground","TextField.foreground","TextArea.foreground","List.foreground","Table.foreground","ComboBox.foreground"})UIManager.put(k,text);for(String k:new String[]{"List.selectionBackground","Table.selectionBackground","ToggleButton.selectedBackground"})UIManager.put(k,selected);UIManager.put("TitlePane.menuBarEmbedded",Boolean.FALSE);UIManager.put("Component.borderColor",line);UIManager.put("Component.arc",8);UIManager.put("Button.arc",8);UIManager.put("TextComponent.arc",7);UIManager.put("Component.focusWidth",1);UIManager.put("defaultFont",new Font("Segoe UI",Font.PLAIN,13));SwingUtilities.updateComponentTreeUI(frame);root.setBackground(bg);sidebar.setBackground(panel);tabs.setUI(new HiddenTabsUI());save.setBackground(useDark?new Color(128,180,251):new Color(36,94,193));save.setForeground(useDark?new Color(8,25,46):Color.WHITE);frame.repaint();}catch(Exception ex){error("Theme",ex);}}
 private String friendlyAccount(WCEditorSaveDiscovery.Entry e){String name=e.label;if("Steam".equals(e.platform)&&e.path.getFileName().toString().startsWith("st_")){String id=e.path.getFileName().toString().substring(3);String known=nomanssave.aH.getProperty("KnownPlayers."+id);if(known!=null&&!known.isEmpty())name=known;}if("GOG".equals(e.platform))name="GOG saves";if(e.platform.startsWith("Xbox"))name="Xbox account · "+e.path.getFileName().toString().substring(0,Math.min(12,e.path.getFileName().toString().length()));return name.length()>29?name.substring(0,26)+"…":name;}
 private void scan(){rescan.setEnabled(false);new SwingWorker<java.util.List<WCEditorSaveDiscovery.Entry>,Void>(){protected java.util.List<WCEditorSaveDiscovery.Entry> doInBackground(){return WCEditorSaveDiscovery.scan();}protected void done(){try{java.util.List<WCEditorSaveDiscovery.Entry> entries=get();sources.clear();for(WCEditorSaveDiscovery.Entry e:entries)sources.addElement(e);if(sources.isEmpty())status.setText("No supported save folders found. Add a custom folder.");}catch(Exception ex){error("Save discovery",ex);}finally{rescan.setEnabled(true);}}}.execute();}
 private void openSelected(){WCEditorSaveDiscovery.Entry e=sourceList.getSelectedValue();if(e==null)return;try{if(WCEditorStorage.open(app,e)){refreshStatus();showNative(0);}}catch(Exception ex){error("Open save account",ex);}}
 private void chooseFolder(){JFileChooser c=new JFileChooser();c.setDialogTitle("Open save folder");c.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);if(c.showOpenDialog(frame)==JFileChooser.APPROVE_OPTION){try{if(WCEditorStorage.open(app,c.getSelectedFile().toPath())){refreshStatus();showNative(0);}}catch(Exception ex){error("Open save folder",ex);}}}
 public void showNative(int index){if(index<0||index>=tabs.getTabCount())return;if(!tabs.isEnabledAt(index)){JOptionPane.showMessageDialog(frame,"This section is not available in the selected save. Choose a save with that data first.","Select a save",JOptionPane.INFORMATION_MESSAGE);syncSection();return;}tabs.setSelectedIndex(index);syncSection();}
 private void syncSection(){if(navigating)return;navigating=true;try{int index=tabs.getSelectedIndex();Section chosen=null;for(Section s:sections)if(s.index==index)chosen=s;if(chosen==null)return;sectionPicker.setSelectedItem(chosen);JToggleButton b=navButtons.get(chosen.group);if(b!=null)b.setSelected(true);subnav.removeAll();for(Section s:sections)if(s.group.equals(chosen.group)&&(!"More".equals(s.group)||s.index==index)){JButton sb=action(s.title,()->showNative(s.index));sb.setMargin(new Insets(6,7,6,7));sb.setEnabled(tabs.isEnabledAt(s.index));if(s.index==index)sb.putClientProperty("JButton.buttonType","borderless");subnav.add(sb);}subnav.revalidate();subnav.repaint();if(index==inventoryIndex)inventory.refresh();if(index==warpIndex)warp.refresh();if(index==baseJsonIndex)bases.refresh();if(index==corvetteIndex)corvettes.refresh();if(index==codexIndex)codex.refresh();if(index<14)inventory.refreshNativePanel(index);refreshStatus();}catch(Exception ex){error("Navigation",ex);}finally{navigating=false;}}
 private void refreshStatus(){try{eY r=(eY)field("aK"),a=(eY)field("aN");boolean dirty=(Boolean)field("aL"),adirty=(Boolean)field("aO");if(r!=lastRoot){lastRoot=r;saveBaseline=r==null?null:r.bE();}else if(previousSaveDirty&&!dirty)saveBaseline=r==null?null:r.bE();if(a!=lastAccount){lastAccount=a;accountBaseline=a==null?null:a.bE();}else if(previousAccountDirty&&!adirty)accountBaseline=a==null?null:a.bE();previousSaveDirty=dirty;previousAccountDirty=adirty;
  String name=((JLabel)field("U")).getText(),storage=((JLabel)field("P")).getText(),path=((JLabel)field("Q")).getText();context.setText(r==null?"Choose an account and save slot":name);if(path!=null&&path.toLowerCase(java.util.Locale.ROOT).contains("defaultuser"))storage="GOG";source.setText(storage+" · "+compact(path,65));source.setToolTipText(path);slot.setEnabled(((JComboBox)field("R")).isEnabled());revision.setEnabled(((JComboBox)field("S")).isEnabled());slot.repaint();revision.repaint();status.setText((dirty?"Character: unsaved changes":"Character: saved")+(adirty?"   ·   Account: unsaved changes":"")+(r==null?"   ·   No character loaded":""));save.setEnabled(r!=null||a!=null);for(Section s:sections)if(s.index==warpIndex||s.index==inventoryIndex||s.index==baseJsonIndex||s.index==corvetteIndex)tabs.setEnabledAt(s.index,r!=null);
 }catch(Exception ex){status.setText("Waiting for the save editor…");}}
 private void commitFocus(){Component c=frame.getFocusOwner();if(c instanceof G)((G)c).N();}
 private void reviewSave(){try{commitFocus();eY r=(eY)field("aK"),a=(eY)field("aN");boolean dirty=(Boolean)field("aL"),adirty=(Boolean)field("aO");JPanel p=new JPanel(new BorderLayout(8,8));JTextArea details=new JTextArea(25,84);details.setEditable(false);details.setFont(new Font(Font.MONOSPACED,Font.PLAIN,12));String text="";if(dirty)text+="CHARACTER SAVE\n"+WCEditorReview.describe(saveBaseline,r);if(adirty)text+="\nACCOUNT DATA\n"+WCEditorReview.describe(accountBaseline,a);details.setText(text);details.setCaretPosition(0);p.add(new JScrollPane(details),BorderLayout.CENTER);JCheckBox sc=new JCheckBox("Write selected character save",dirty),ac=new JCheckBox("Write this account's changes",adirty);sc.setEnabled(dirty);ac.setEnabled(adirty);p.add(row(sc,ac),BorderLayout.NORTH);p.add(new JLabel("Close No Man’s Sky before writing. A verified backup must succeed first."),BorderLayout.SOUTH);if(JOptionPane.showConfirmDialog(frame,p,"Review native save changes",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE)!=JOptionPane.OK_OPTION)return;if(r!=field("aK")||a!=field("aN"))throw new IllegalStateException("Selected save changed. Review again.");if(sc.isSelected()){invoke("n");if((Boolean)field("aL"))throw new IOException("The character save did not finish. Check the editor error and compatibility log.");}if(ac.isSelected()){invoke("m");if((Boolean)field("aO"))throw new IOException("The account save did not finish. Check the editor error and compatibility log.");}refreshStatus();}catch(Exception ex){error("Save changes",ex);}}
 private JPanel jsonPanel(){JPanel p=new JPanel(new BorderLayout(10,18));p.setBorder(new EmptyBorder(24,24,24,24));p.add(label("JSON workspace",24,true),BorderLayout.NORTH);JPanel actions=stack();actions.add(label("Character save",15,true));actions.add(Box.createVerticalStrut(8));actions.add(row(menuButton("Edit Raw JSON"),menuButton("Export JSON"),menuButton("Import JSON")));actions.add(Box.createVerticalStrut(28));actions.add(label("Account data",15,true));actions.add(Box.createVerticalStrut(8));actions.add(row(menuButton("Edit Account JSON")));actions.add(Box.createVerticalStrut(22));actions.add(new JLabel("<html>The native JSON editor retains text/tree views, validation, find and exact integer values.<br>Selected-base JSON tools are under Bases → Base JSON.</html>"));p.add(actions,BorderLayout.CENTER);return p;}
 private JButton menuButton(String title){return action(title,()->{JMenuItem m=findMenu(frame.getJMenuBar(),title);if(m==null||!m.isEnabled()){JOptionPane.showMessageDialog(frame,"Load the relevant save or account first.");return;}m.doClick();});}
 private static JMenuItem findMenu(MenuElement parent,String title){for(MenuElement e:parent.getSubElements()){if(e instanceof JMenuItem&&title.equals(((JMenuItem)e).getText()))return(JMenuItem)e;JMenuItem nested=findMenu(e,title);if(nested!=null)return nested;}return null;}
 private JPanel toolsPanel(){JPanel p=new JPanel(new BorderLayout(10,18));p.setBorder(new EmptyBorder(24,24,24,24));p.add(label("Tools & settings",24,true),BorderLayout.NORTH);JPanel body=stack();body.add(label("Appearance",15,true));body.add(Box.createVerticalStrut(10));body.add(row(action("Wonder dark",()->applyTheme(true)),action("Wonder light",()->applyTheme(false)),menuButton("Settings")));body.add(Box.createVerticalStrut(24));body.add(label("Global inventory tools",15,true));body.add(Box.createVerticalStrut(10));for(String[] row:new String[][]{{"Recharge All Technology","Refill All Stacks","Recharge Base Planters"},{"Expand All Inventories","Enable All Slots","Repair All Slots / Technology"}}){JPanel line=row();for(String title:row)line.add(menuButton(title));body.add(line);body.add(Box.createVerticalStrut(10));}body.add(Box.createVerticalStrut(14));body.add(row(menuButton("Test Mode"),menuButton("Save File As"),action("Compatibility report",()->WCCosmosHooks.exportReport(app))));body.add(Box.createVerticalStrut(20));body.add(new JLabel("All original File, Edit, View and Help menu commands remain available."));p.add(body,BorderLayout.CENTER);return p;}
 private JPanel archivePanel(){JPanel p=new JPanel(new BorderLayout(12,18));p.setBorder(new EmptyBorder(24,24,24,24));p.add(label("Expedition archive",24,true),BorderLayout.NORTH);String[][] data={{"Pioneers","March 31, 2021"},{"Beachhead","May 17, 2021"},{"Omega","February 15, 2024"},{"Adrift","May 29, 2024"},{"Aquarius","September 4, 2024"}};JPanel body=stack();body.add(new JLabel("Original expedition launch dates · selected entries"));body.add(Box.createVerticalStrut(15));JTable table=new JTable(data,new String[]{"Expedition","Original day 1"}){public boolean isCellEditable(int r,int c){return false;}};table.setRowHeight(34);JScrollPane scroll=new JScrollPane(table);scroll.setMaximumSize(new Dimension(700,205));body.add(scroll);body.add(Box.createVerticalStrut(25));JTextArea text=new JTextArea("Expedition replay is unavailable in this release.\n\nPast expeditions require matching season-cache data and compatibility checks for the installed game version. Changing the PC date alone is not a verified replay method. Original and Redux editions need separate entries.\n\nThis editor does not change the PC clock or install expedition data.");text.setLineWrap(true);text.setWrapStyleWord(true);text.setEditable(false);text.setOpaque(false);text.setMaximumSize(new Dimension(760,180));body.add(text);body.add(action("Replay project reference",()->browse("https://github.com/cwmonkey/nms-expeditions")));p.add(body,BorderLayout.CENTER);return p;}
 private void browse(String url){try{Desktop.getDesktop().browse(new java.net.URI(url));}catch(Exception ex){error("Open reference",ex);}}
 private void openBackups(){try{Desktop.getDesktop().open(WCCosmosBackup.home.resolve("backups").toFile());}catch(Exception ex){error("Backups",ex);}}
 private void about(){
  JPanel body=stack();
  JTextArea text=new JTextArea("Wonder Codex Editor "+WCEditorLauncher.VERSION+"\n\nSave tools for your travels across No Man's Sky.\nBuilt on No Man's Sky Save Editor 1.21.0 by GoatFungus,\nwith the original editor's menus and data operations retained.\n\nCorvette Optimizer is independent software by TAZmd.\nIt is not owned by Wonder Codex and is installed separately.\nWonder Codex checks the file changes and provides update notices.");
  text.setEditable(false);text.setOpaque(false);text.setAlignmentX(Component.LEFT_ALIGNMENT);body.add(text);body.add(Box.createVerticalStrut(12));
  JButton goatfungus=action("No Man's Sky Save Editor by GoatFungus · GitHub",()->browse("https://github.com/goatfungus/nmssaveeditor"));
  goatfungus.setName("about.goatfungus");goatfungus.setBorderPainted(false);goatfungus.setContentAreaFilled(false);goatfungus.setHorizontalAlignment(SwingConstants.LEFT);goatfungus.setAlignmentX(Component.LEFT_ALIGNMENT);goatfungus.setToolTipText("https://github.com/goatfungus/nmssaveeditor");body.add(goatfungus);
  JButton tazmd=WCEditorTazDialog.creatorLink();tazmd.setAlignmentX(Component.LEFT_ALIGNMENT);body.add(tazmd);
  JOptionPane.showMessageDialog(frame,body,"About Wonder Codex Editor",JOptionPane.INFORMATION_MESSAGE);
 }

 private void error(String operation,Throwable ex){ex.printStackTrace();WCCosmosBackup.log("DESKTOP "+operation+": "+ex);JOptionPane.showMessageDialog(frame,ex.getMessage(),operation,JOptionPane.ERROR_MESSAGE);}
 private static String compact(String s,int n){if(s==null)return "";return s.length()>n?"…"+s.substring(s.length()-n):s;}
 private static String html(String s){return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;");}
 private static final class Section{final int index;final String title,group;Section(int i,String t,String g){index=i;title=t;group=g;}public String toString(){return title;}}
 private static final class HiddenTabsUI extends BasicTabbedPaneUI{protected int calculateTabAreaHeight(int placement,int runs,int height){return 0;}protected int calculateTabAreaWidth(int placement,int runs,int width){return 0;}protected void paintTabArea(Graphics g,int placement,int selected){}protected void paintContentBorder(Graphics g,int placement,int selected){}}
}
